### ISSUE TITLE
Cannot locate res/raw/opening.mp4

### ISSUE THREAD

**Issue by jordaninthesky** [Rinnegatamante/ff4_vita#3]
Extracted the whole APK but still unable to find the video.  Please advise!

**Comment by Rinnegatamante** [comment]
Apk coming from Play Store does have said file. Don't know what more to say.

**Comment by jordaninthesky** [comment]
I found that locating the apk file via the referenced source on the readme.md provided a truncated version of the apk (~6MB), unlike the outcome I had with FFIII.  The truncated version had no openining.mp4 and no libff4.so.  It did have a libff4a.so which, even if renamed, didn't work with the apk.

**Comment by jordaninthesky** [comment]
aforementioned source: https://stackoverflow.com/questions/11012976/how-do-i-get-the-apk-of-an-installed-app-without-root-access
